// import { Geist, Geist_Mono } from "next/font/google";
'use client';
import { ReactFlowProvider } from "@xyflow/react";
import "./globals.css";
import AuthProvider from "../context/Authprovider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <ReactFlowProvider>
      <AuthProvider>
       {children}
        </AuthProvider>
        </ReactFlowProvider>
      </body>
    </html>
  );
}
